general:
  debug: false
  #will check for a newer version and alert any OP when they login to the server
  checkforupdate: true
  #Set to true to only allow Vivecraft players to play.
  vive-only: false
  #The message to show kicked non-vive players.
  vive-only-kickmessage: This server is configured for Vivecraft players only.
  #Ticks to wait before kicking a player. The player's client must send a Vivecraft VERSION info in that time.
  vive-only-kickwaittime: 10
  printmoney: false
SendPlayerData:
  #Send player data to all clients with Vivecraft
  enabled: true
CreeperRadius:
  #Distance from a Vivecraft player before creeper starts to swell up (vanilla is 3)
  enabled: true
  radius: 1.75
setSpigotConfig:
  enabled: true
  #Increase these if you get rubber banding when teleporting.
  movedWronglyThreshold: 15
  movedTooQuickly: 64
pvp:
  #Allows Standing VR players to Attack other Standing VR Players
  VRvsVR: true 
  #Allows Standing VR Players to attack Non VR players
  VRvsNONVR: true
  #Allows  Seated VR Players to attack normal players.
  SEATEDVRvsNONVR: true
  #Allows Standing VR Players to attack Seated VR Players
  VRvsSEATEDVR: true
bow:
  #Archery damage multiplier for Vivecraft (standing) users. Set to 1 to disable
  standingmultiplier: 2
  #Archery damage multiplier for Vivecraft (seated) users. Set to 1 to disable
  seatedmultiplier: 1
  #Headshot damage multiplier for Vivecraft (standing) users. Set to 1 to disable
  standingheadshotmultiplier: 3
  #Headshot damage multiplier for Vivecraft (seated) users. Set to 1 to disable
  seatedheadshotmultiplier: 2
  #Set if players can headshot mobs (only horizontal mobs)
  headshotmobs: true
permissions:
  #Permission group for Vive users
  vivegroup: vive.vivegroup
  #Permission group for non-Vive users
  non-vivegroup: vive.non-vivegroup
  #Permission group for vive users in free move mode.
  freemovegroup: vive.freemovegroup
welcomemsg:
  enabled: true
  #Remove message to not send. ex: leaveMessage:
  welcomeVR: Welcome, VR user!
  welcomenonVR: Welcome, &player!
  welcomeSeated: Welcome Seated Player!
  leaveMessage: &player has left the server!
climbey:
  #Allows use of jump_boots and climb_claws. Provide with /give (player) climb_claws | jump_boots
  enabled: false